# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 13:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Game Date')),
                ('opponent', models.CharField(max_length=50)),
                ('venue', models.CharField(choices=[('H', 'Home'), ('A', 'Away'), ('N', 'Neutral Venue')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completions', models.IntegerField()),
                ('attempts', models.IntegerField()),
                ('pass_rating', models.DecimalField(decimal_places=1, max_digits=4)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('distance', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0.5)])),
                ('field_half', models.CharField(choices=[('OWN', 'Own'), ('OPP', "Opponent's")], max_length=3)),
                ('yard_line', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0.5)])),
                ('quarter', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('time', models.TimeField()),
                ('gain', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('complete', models.BooleanField(default=False)),
                ('outcome', models.CharField(choices=[(('TD',), 'Touchdown'), (('INT',), 'Interception'), (('PA',), 'Pass Attempt'), ('SK', 'Sack')], max_length=3)),
                ('vid_url', models.CharField(max_length=50, null=True)),
                ('vid_url_alt', models.CharField(max_length=50, null=True)),
                ('vid_url_alt2', models.CharField(max_length=50, null=True)),
                ('air_yards', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('accurate', models.BooleanField(default=True)),
                ('note', models.TextField(max_length=300, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('jersey_no', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('imageUrl', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Team'),
        ),
        migrations.AddField(
            model_name='play',
            name='passer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_passer', to='project.Player'),
        ),
        migrations.AddField(
            model_name='play',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_receiver', to='project.Player'),
        ),
        migrations.AddField(
            model_name='performance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Team'),
        ),
    ]
